name: ms-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    #- uses: microsoft/setup-msbuild@v1.3.1

    - name: Download ut.hpp
      run: |
        curl -O https://raw.githubusercontent.com/boost-ext/ut/master/include/boost/ut.hpp

    - name: Compile
      run: |
        cl /std:c++latest /permissive- /utf-8 /W4 /WX /EHsc test.cpp

    - name: Run
      run: ./test.exe
